# Generated by Django 3.1.7 on 2021-03-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
